# Alias List
alias ll='ls -lh'
alias l='ls -lh'

alias o='open . &'
alias ,='cd ..'

# Git
alias g='git status'
alias gs='git show'
alias gl='git log'
alias gb='git branch -a'
alias gd='git diff'
alias ga='git add'
alias gc='git commit -m'
alias gca='git commit -v -a'
alias gprom='git pull --rebase origin master'
alias gpom='git push origin master'
alias grh='git reset --hard'

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

export PS1="\u@\h \W \[\e[32m\]\\$\[\e[m\] ""]]"
source "$HOME/.cargo/env"
